add failure attempts when creating the bundle

diff --git a/policies/operators/acs/central/init-bundle/job.yml b/policies/operators/acs/central/init-bundle/job.yml
--- a/policies/operators/acs/central/init-bundle/job.yml
+++ b/policies/operators/acs/central/init-bundle/job.yml
@@ -39,9 +39,26 @@ spec:
                 sleep 5
             done
 
+            # attempt to create init-bundle
+            # on failure attempt to delete the bundle
+            attempt_counter=0
+            max_attempts=5
             echo "Configuring cluster-init bundle"
             export DATA={\"name\":\"local-cluster\"}
-            curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA https://central/v1/cluster-init/init-bundles
+            until (curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA --fail https://central/v1/cluster-init/init-bundles); do
+                if [ ${attempt_counter} -eq ${max_attempts} ];then
+                  echo "Max attempts to create bundle reached"
+                  exit 1
+                fi
+
+                echo attempting to delete the bundle
+                curl -k -X DELETE -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA https://central/v1/cluster-init/init-bundles
+
+                printf '.'
+                attempt_counter=$(($attempt_counter+1))
+                echo "Made create bundle attempt $attempt_counter, waiting..."
+                sleep 5
+            done
 
             echo "Bundle received"
 
